version: 2.1
description: Orb for firebase deploy.

orbs:
  hugo: circleci/hugo@0.4.1

jobs:
  deploy:
    description: Deploy to firebase
    docker: 
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: npm ci
      - run: npm run deploy -- --token=$FIREBASE_TOKEN

workflows:
  version: 2
  deploy:
    jobs:
      - hugo/build
      - deploy:
        filters:
          branches:
            only: master
        requires:
          - hugo/build