version: 2.1
description: Orb for firebase deploy.


jobs:
  deploy:
    description: Deploy to firebase
    docker: 
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: npm ci
      - run: npm run deploy -- --token=$FIREBASE_TOKEN

orbs:
  hugo: circleci/hugo@0.2

workflows:
  deploy:
    jobs:
      - hugo/build:
          html-proofer: true
          version: '0.55'
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - hugo/build