on: [push]
name: Deploy Hugo to Firebase
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - uses: ryank90/action-hugo-firebase-deploy@v1.0.1
      with:
        firebase-token: ${{ secrets.firebase_token }}
        alias: definitely-not-reptilian
        hugo-params: -D
